### ISSUE TITLE
Unable to build Xamarin.Android app.

### ISSUE THREAD

**Issue by santolex** [OpenTl/OpenTl.ClientApi#21]
Repro steps:
1. Create Xamarin.Android app
2. Add OpenTl.ClientApi using Nuget.
3.Build

After build you should get the message. 

Warning		Failed to read 'C:\Users\sum90\.nuget\packages\system.runtime.loader\4.3.0\lib\MonoAndroid10\_._' with debugging symbols. Retrying to load it without it. Error details are logged below.	And			
Warning		System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)	And		
Error       Exception while loading assemblies: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA0009: Error while loading assembly: C:\Users\sum90\.nuget\packages\system.runtime.loader\4.3.0\lib\MonoAndroid10\_._ ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
   at Xamarin.Android.Tasks.ResolveAssemblies.ResolveRuntimeAssemblyForReferenceAssembly(LockFile lockFile, DirectoryAssemblyResolver resolver, String assemblyPath)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	And

**Comment by vik-borisov** [comment]
@santolex Hi!
Are you sure this is an OpeTl.Client library problem?
I do not see a call stack mention

**Comment by vik-borisov** [comment]
Still relevant?

**Comment by kosmakoff** [comment]
I  also happen to have the same problem. Just installed the Xamarin tools, added OpenTl.Client package to it - and it doesn't build. Can it be because this Fody tool messes with output binary in some way?

**Comment by vik-borisov** [comment]
@kosmakoff may be.
There are no plans to support Xamarin yet
