### ISSUE TITLE
FileMigrationException

### ISSUE THREAD

**Issue by dehqan** [OpenTl/OpenTl.ClientApi#23]
Hi, i use 'DownloadAllFilePartsAsync' method, where sometimes this exception occurs:

`OpenTl.ClientApi.MtProto.Exceptions.FileMigrationException: File located on a different DC: 1.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenTl.ClientApi.MtProto.Services.RequestSenderService.<SendRequestAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenTl.ClientApi.Services.FileService.<DownloadFilePartAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenTl.ClientApi.Services.FileService.<DownloadAllFilePartsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
`
How can i handle this exception?
Thanks.

**Comment by vik-borisov** [comment]
Hi, @dehqan! 
The library should handle such errors.
Can you send me a log?
https://github.com/OpenTl/OpenTl.ClientApi/wiki/How-to-attach-a-logger

**Comment by dehqan** [comment]
[2018-10-04-FULL.log](https://github.com/OpenTl/OpenTl.ClientApi/files/2446732/2018-10-04-FULL.log)
[2018-10-04-FULL_older.log](https://github.com/OpenTl/OpenTl.ClientApi/files/2446733/2018-10-04-FULL_older.log)

These are the logs when Exception occurred.
