### ISSUE TITLE
RSC Public Key -----END RSA PUBLIC KEY not found

### ISSUE THREAD

**Issue by Haizanjs** [OpenTl/OpenTl.ClientApi#26]
**Thanks in advanced**

![image](https://user-images.githubusercontent.com/27821536/47586342-d2fd5500-d957-11e8-8791-d2133ca3a8f8.png)

Loaded from a JSON File as a JObject then casted ().

```csharp
        var settings = new FactorySettings
        {
            AppHash = (string)TelegramUser[3],
            AppId = (int)TelegramUser[2],
            ServerAddress = (string)TelegramUser[5],
            ServerPublicKey = (string)TelegramUser[7],
            ServerPort = (int)TelegramUser[6],
            SessionTag = "session", // by defaut
            Properties = new ApplicationProperties
            {
                AppVersion = "1.0.0", 
                DeviceModel = "PC", 
                LangCode = "en", 
                LangPack = "tdesktop", 
                SystemLangCode = "en", 
                SystemVersion = "Win 10 Pro" 
            }
        };
```

Error Exception:

```
System.IO.IOException
  HResult=0x80131620
  Message=-----END RSA PUBLIC KEY not found
  Source=OpenTl.BouncyCastle
  StackTrace:
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.LoadObject(String type)
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.ReadPemObject()
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
   at OpenTl.Common.Crypto.RSAHelper.GetFingerprint(String key)
   at OpenTl.Common.Auth.Client.Step2ClientHelper.GetRequest(TResPQ resPq, String publicKey, Byte[]& newNonce)
   at OpenTl.ClientApi.MtProto.Layers.Handshake.Adapters.HandshakeHandlerAdapter.ChannelRead0(IChannelHandlerContext ctx, IObject msg)
   at DotNetty.Transport.Channels.SimpleChannelInboundHandler`1.ChannelRead(IChannelHandlerContext ctx, Object msg)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at OpenTl.ClientApi.MtProto.Services.RequestSenderService.<SendRequestAsync>d__12`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at OpenTl.ClientApi.Services.AuthService.<SendCodeAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 529
   at Telegram_Voids.<Telegram_InitAsync>d__0.MoveNext() in F:\Programs\SelfCreated\MoneyTime\MoneyTime\Telegram.cs:line 49
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\AsyncMethodBuilder.cs:line 1034
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state) in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1273
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 954
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 901
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1250
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 819
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in f:\dd\ndp\clr\src\BCL\system\threading\threadpool.cs:line 1161

```

**Comment by seventhpan** [comment]
![image](https://user-images.githubusercontent.com/35943180/47632148-e12fb900-db83-11e8-906f-c3d1e7f9fba2.png)
you should use  &#xA;  to relace \n in xml

**Comment by Haizanjs** [comment]
Fixed!

```csharp
var settings = new FactorySettings
        {
            AppHash = (string)TelegramUser[3],
            AppId = (int)TelegramUser[2],
            ServerAddress = (string)TelegramUser[5],
            ServerPublicKey = @"-----BEGIN RSA PUBLIC KEY-----CONTENTS INSIDE-----END RSA PUBLIC KEY-----",
            ServerPort = (int)TelegramUser[6],
            SessionTag = "session", // by defaut
            Properties = new ApplicationProperties
            {
                AppVersion = "1.0.0", 
                DeviceModel = "PC", 
                LangCode = "en", 
                LangPack = "tdesktop", 
                SystemLangCode = "en", 
                SystemVersion = "Win 10 Pro" 
            }
        };
```

**Comment by dojo90** [comment]
@seventhpan I had to add "&#xA;" in my XML file to get it working. Maybe this should be fixed
