### ISSUE TITLE
Dotnetty Exception downloading images

### ISSUE THREAD

**Issue by bsod79** [OpenTl/OpenTl.ClientApi#29]
Hello,

With the latest version of OpenTL from Nuget my application starts getitng a lot of error when downloading profile image. Please refer to the sampleapplication attached (adapted from sampleapp.)
[OpenTl.ClientApi.SampeApp.zip](https://github.com/OpenTl/OpenTl.ClientApi/files/2649196/OpenTl.ClientApi.SampeApp.zip)

```
Exception thrown: 'System.NullReferenceException' in OpenTl.Schema.dll ("Object reference not set to an instance of an object.")
   at System.Object.GetType()
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Serialize(Object obj, IByteBuffer buffer, SerializationMetadata _)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Serialize(Object obj, IByteBuffer buffer, SerializationMetadata _)
   at OpenTl.Schema.Serialization.Serializer.Serialize(Object obj)
   at OpenTl.ClientApi.MtProto.Layers.Secure.Codecs.SecureRequestEncoder.Encode(IChannelHandlerContext context, IObject message, IByteBuffer output)
   at DotNetty.Codecs.MessageToByteEncoder`1.WriteAsync(IChannelHandlerContext context, Object message)
```

Exception thrown: 'DotNetty.Codecs.EncoderException' in mscorlib.dll ("")

![image](https://user-images.githubusercontent.com/5484476/49577404-973aaf80-f947-11e8-8111-8d139d09e7f4.png)

**Comment by vik-borisov** [comment]
@slasher79 Hi!
All reference properties must be filled in the request.

**Comment by bsod79** [comment]
> @slasher79 Hi!
> All reference properties must be filled in the request.

Hello @vik-borisov 
What do you mean with the above? In the code? Since the code was working before the update from nuget.

**Comment by vik-borisov** [comment]
@slasher79 
The new version has updated the scheme. Check whether all the properties of the reference types you have filled out the requests that you send

**Comment by bsod79** [comment]
Thanks a lot @vik-borisov 

I double checked and modified the code with 

`var img = DownloadImage(new TInputFileLocation()
            {
                LocalId = photosize.Location.LocalId,
                Secret = photosize.Location.Secret,
                VolumeId = photosize.Location.VolumeId,
                FileReference = photo.FileReference
            });`

I was missing "FileReference".

bye

**Comment by boexler** [comment]
@slasher79 thanks for your snippet! I had exactly the same exceptions!
