### ISSUE TITLE
I Send Message To SuperGroup throw Exception Please Help Me

### ISSUE THREAD

**Issue by adelhoss** [OpenTl/OpenTl.ClientApi#49]
Hi My Friends
I Need send Message To SuperGroup 
According this link from api telegram :
https://core.telegram.org/api/channel
SupperGroup Is new
I Use Your PowerFul Liobrary :
Your Library Show megagroup Property Please See This ScreenShot
[megagroup is true](https://www.mediafire.com/convkey/53b9/tqai0uwh5uilq2jzg.jpg)
nut when call MessagesService.SendMessageAsync :
[sendmessage](https://www.mediafire.com/convkey/f98e/h6ssq8y49j8b1ktzg.jpg)
after send message success exception throw :
[exception](https://www.mediafire.com/convkey/7f79/ffenywu9hh6izh6zg.jpg)
please help me thx

**Comment by adelhoss** [comment]
Project Is Discontinue ????????

**Comment by KoalaBear84** [comment]
Unfortunately yes. :(

**Comment by adelhoss** [comment]
You can not help me friends ?

**Comment by adelhoss** [comment]
Message Successfully send and then
After I Send Message Exception is throw :
```
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelRead(IChannelHandlerContext context, Object message)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenTl.ClientApi.MtProto.Services.RequestSenderService.<SendRequestAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenTl.ClientApi.Services.MessagesService.<SendMessageAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DropBoxDownloader.Form6.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e)
```

**Comment by adelhoss** [comment]
Alternative Library for C# ?

**Comment by KoalaBear84** [comment]
Maybe this:

https://github.com/sochix/TLSharp

**Comment by adelhoss** [comment]
Oh No TlSharp Very Very Bad Library .

**Comment by KoalaBear84** [comment]
Aww. This then? But it is probably a little more low level, so it needs more programming. If this doesn't fit, then I can't help. Sad to see there is not an easy and maintained C# lib.

https://github.com/tdlib/td

**Comment by adelhoss** [comment]
After a few Hour My Problem Solved ...
Solution Very Very Simple :
 Please Wait A Few Hour .
Telegram Block My Account Temporary.
Your Library Is Best Library For Telegram in .NET .
Please Continue Support .
THx .
