### ISSUE TITLE
'RequestGetMessagesViews' throws an exception

### ISSUE THREAD

**Issue by Kati3e** [OpenTl/OpenTl.ClientApi#5]
**Example Code**
```c#
var inputPeer = new TInputPeerUser
{
    AccessHash = unchecked((long)XXXXXXXXXXXXX),
    UserId = XXXXXXXX
};

TVector<int> idList = new TVector<int>();
idList.Items.Add(XXXXX);

try
{
    var reply = await _clientApi.CustomRequestsService.SendRequestAsync(
        new RequestGetMessagesViews
        {
            Peer = inputPeer,
            Id = idList,
            Increment = false
        }, CancellationToken.None);
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

**Exception**

```
DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderExce
ption' was thrown. ---> System.ArgumentException: Cannot create an instance of O
penTl.Schema.TVector`1[T] because Type.ContainsGenericParameters is true.
   at System.RuntimeType.CreateInstanceCheckThis()
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipChec
kThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean s
kipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at OpenTl.Schema.Serialization.Serializer.DeserializeObject(IByteBuffer buffe
r, TypeInfo propertyTypeInfo)
   at OpenTl.Schema.Serialization.Serializer.DeserializeByType(IByteBuffer buffe
r, TypeInfo typeInfo)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.De
serialize(IByteBuffer buffer, SerializationMetadata metadata)
   at OpenTl.Schema.Serialization.Serializer.DeserializeByType(IByteBuffer buffe
r, TypeInfo typeInfo)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.De
serialize(IByteBuffer buffer, SerializationMetadata metadata)
   at OpenTl.Schema.Serialization.Serializer.DeserializeObject(IByteBuffer buffe
r, TypeInfo propertyTypeInfo)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.ArrayOfContainerMess
ageSerializer.Deserialize(IByteBuffer buffer, SerializationMetadata metadata)
   at OpenTl.Schema.Serialization.Serializer.DeserializeObject(IByteBuffer buffe
r, TypeInfo propertyTypeInfo)
   at OpenTl.ClientApi.MtProto.Layers.Secure.Codecs.SecureRequestDecoder.Decode(
IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext con
text, IByteBuffer input, List`1 output)
   --- End of inner exception stack trace ---
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext con
text, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelRead(IChannelHandlerContext co
ntext, Object message)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRea
d(Object msg)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at OpenTl.ClientApi.MtProto.Services.RequestSenderService.<SendRequestAsync>d
__12`1.MoveNext()
   at OpenTl.ClientApi.MtProto.Services.RequestSenderService.<SendRequestAsync>d
__12`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at OpenTl.ClientApi.MtProto.Services.RequestSenderService.<SendRequestAsync>d
__12`1.MoveNext()
```

**Comment by vik-borisov** [comment]
@Kati3e 
fixed in version 0.4.*
