### ISSUE TITLE
Can't deserialize message:

### ISSUE THREAD

**Issue by Max0nyM** [OpenTl/OpenTl.ClientApi#55]
ERROR. It becomes time by time, anyway to fix this?

2020-12-06 17:34:23,224 [18] ERROR OpenTl.ClientApi.MtProto.Layers.Secure.Codecs.SecureRequestDecoder.? - #1437640440660576064: Can't deserialize message:

2020-12-06 17:34:23,231 [18] ERROR OpenTl.ClientApi.MtProto.Layers.Top.Adapters.TopHandlerAdapter.? - #1437640440660576064: Caught exception
DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderException' was thrown.
 ---> System.NotSupportedException: Specified method is not supported.
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Deserialize(IByteBuffer buffer, SerializationMetadata typeMetadata)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.VectorSerializer.Deserialize(IByteBuffer buffer, SerializationMetadata metadata)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Deserialize(IByteBuffer buffer, SerializationMetadata typeMetadata)
   at OpenTl.Schema.Serialization.Serializer.Deserialize(IByteBuffer buffer)
   at OpenTl.ClientApi.MtProto.Layers.Secure.Codecs.SecureRequestDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End of inner exception stack trace ---
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelRead(IChannelHandlerContext context, Object message)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)
2020-12-06 17:34:23,236 [18] ERROR OpenTl.ClientApi.MtProto.Services.RequestService.? - #1437640440660576064: All requests was processed with error
DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderException' was thrown.
 ---> System.NotSupportedException: Specified method is not supported.
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Deserialize(IByteBuffer buffer, SerializationMetadata typeMetadata)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.VectorSerializer.Deserialize(IByteBuffer buffer, SerializationMetadata metadata)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Deserialize(IByteBuffer buffer, SerializationMetadata typeMetadata)
   at OpenTl.Schema.Serialization.Serializer.Deserialize(IByteBuffer buffer)
   at OpenTl.ClientApi.MtProto.Layers.Secure.Codecs.SecureRequestDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End of inner exception stack trace ---
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelRead(IChannelHandlerContext context, Object message)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)

**Comment by KoalaBear84** [comment]
I'm not aware of a fix. Unfortunately this library isn't maintained anymore.

**Comment by Max0nyM** [comment]
Do you know any other Library for C# ?:)

**Comment by KoalaBear84** [comment]
Sadly not. Wonder myself too. For me receiving realtime messages would be almost enough. Sending would also be nice.
